### PR TITLE
Allow setting child admins in AdminOptions

### PR DESCRIPTION
**Pull request by gremo**
Waiting for tests refactoring (see #18) to write some tests.

## Changelog

```markdown
### Added
- Support for setting child admins in `AdminOptions`
```

### CODE REVIEW

**Comment by kunicmarko20** [comment]
tests :smile:

**Comment by kunicmarko20** [comment]
I rebased it for you, would you be interested in providing a behat test for this?

**Comment by gremo** [comment]
> I rebased it for you, would you be interested in providing a behat test for this?

Sorry, unfortunately I don't know behat. I can't.

**Comment by kunicmarko20** [comment]
@gremo I can guide you if you want? If not, just add a unit test and I will merge it

**Comment by gremo** [comment]
I've added a simple test (just like expecting the call for `setTemplate`) in the compiler pass test. Let me know (can you release after this merge? thanks).

**Comment by gremo** [comment]
Can you please release 0.6.0? I'm finalizing a work project which uses this bundle :)

**Review by kunicmarko20 — APPROVED** [review]

**Comment by kunicmarko20** [comment]
@gremo can you check https://github.com/kunicmarko20/SonataAutoConfigureBundle/issues/21 ? I want to fix this before release

**Comment by kunicmarko20** [comment]
you can require `1.x-dev` until the release

**Pull request merged**
