### PR TITLE
Allow setting templates in AdminOptions

### LINKED ISSUE #17: Add the ability to configure admin templates
Right now, since `getTemplates` and `getTemplate($name)` in `AbstractAdmin` re both deprecated, the only way to configure template is using the service definition. Using the annotation, this is a no-sense (just defining a service to change a template).

Templates support can be added this way:

```php
/**
 * @Sonata\AdminOptions(
 *     templates={
 *         "notify": "admin/category/notify.html.twig"
 *     }
 * )
 */
class CategoryAdmin extends AbstractAdmin
{
}
```

### PR DESCRIPTION
**Pull request by gremo**
Closes #17.

## Changelog

```markdown
### Added
- Support for setting templates in `AdminOptions`
```

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Some kind of tests, please.

**Comment by kunicmarko20** [comment]
Also add it to the readme

**Comment by gremo** [comment]
> Some kind of tests, please.

Where I should put these tests?

**Comment by kunicmarko20** [comment]
Add annotation with templates and see if service in the container has these templates, I think there are some similar tests already

**Comment by gremo** [comment]
Update README and added a test (i don't like the way annotation is tested).

**Comment by kunicmarko20** [comment]
> i don't like the way annotation is tested

propose a better way then?

**Comment by gremo** [comment]
> propose a better way then?

I mean, my way... can you check the test?

**Comment by kunicmarko20** [comment]
I see, but that is the only case where that way would work? Also, I would validate that the keys and values are as you set them `"foo": "foo.html.twig"`

**Comment by gremo** [comment]
> I see, but that is the only case where that way would work? Also, I would validate that the keys and values are as you set them `"foo": "foo.html.twig"`

Yes, but i cant understand how `$definition->getMethodCalls()` works...

**Comment by kunicmarko20** [comment]
If I am correct, something like a queue, and when the container gets compiled and definitions become references, then the methods are called.

**Comment by kunicmarko20** [comment]
Thanks @gremo

**Pull request merged**
