### PR TITLE
Symfoy 4 autowiring improvements

### LINKED ISSUE #10: Autowire doesn't work (when admin is injected in another service)
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.44.0 3.45.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.13.0 3.14.0 Symfony SonataBlockBundle
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  3.0.1  This bundle provides caching services
sonata-project/classification-bundle     3.7.1  3.8.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.11.2 3.15.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.0  3.8.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdmin...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.0 1.11.0 Lightweight Exporter library
sonata-project/formatter-bundle          4.1.2  4.1.2  Symfony SonataFormatterBundle
sonata-project/media-bundle              3.17.1 3.18.1 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.5.1  3.5.1  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.9.1  3.10.0 This bundle provides a Site and Page management through cont...
sonata-project/seo-bundle                2.6.2  2.7.0  Symfony SonataSeoBundle
sonata-project/user-bundle               4.2.3  4.2.3  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'

symfony/apache-pack           v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                 v4.2.2  v4.2.2  Symfony Asset Component
symfony/cache                 v4.2.2  v4.2.2  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                v4.2.2  v4.2.2  Symfony Config Component
symfony/console               v4.2.2  v4.2.2  Symfony Console Component
symfony/contracts             v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector          v4.2.2  v4.2.2  Symfony CssSelector Component
symfony/debug                 v4.2.2  v4.2.2  Symfony Debug Component
symfony/debug-bundle          v4.2.2  v4.2.2  Symfony DebugBundle
symfony/debug-pack            v1.0.7  v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection  v4.2.2  v4.2.2  Symfony DependencyInjection Component
symfony/doctrine-bridge       v4.2.2  v4.2.2  Symfony Doctrine Bridge
symfony/dotenv                v4.2.2  v4.2.2  Registers environment variables from a .env file
symfony/event-dispatcher      v4.2.2  v4.2.2  Symfony EventDispatcher Component
symfony/expression-language   v4.2.2  v4.2.2  Symfony ExpressionLanguage Component
symfony/filesystem            v4.2.2  v4.2.2  Symfony Filesystem Component
symfony/finder                v4.2.2  v4.2.2  Symfony Finder Component
symfony/flex                  v1.1.8  v1.1.8  Composer plugin for Symfony
symfony/form                  v4.2.2  v4.2.2  Symfony Form Component
symfony/framework-bundle      v4.2.2  v4.2.2  Symfony FrameworkBundle
symfony/http-foundation       v4.2.2  v4.2.2  Symfony HttpFoundation Component
symfony/http-kernel           v4.2.2  v4.2.2  Symfony HttpKernel Component
symfony/inflector             v4.2.2  v4.2.2  Symfony Inflector Component
symfony/intl                  v4.2.2  v4.2.2  A PHP replacement layer for the C intl extension that includes additi...
symfony/maker-bundle          v1.11.3 v1.11.3 Symfony Maker helps you create empty commands, controllers, form clas...
symfony/monolog-bridge        v4.2.2  v4.2.2  Symfony Monolog Bridge
symfony/monolog-bundle        v3.3.1  v3.3.1  Symfony MonologBundle
symfony/options-resolver      v4.2.2  v4.2.2  Symfony OptionsResolver Component
symfony/orm-pack              v1.0.6  v1.0.6  A pack for the Doctrine ORM
symfony/polyfill-intl-icu     v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring     v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72        v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP vers...
symfony/process               v4.2.2  v4.2.2  Symfony Process Component
symfony/profiler-pack         v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access       v4.2.2  v4.2.2  Symfony PropertyAccess Component
symfony/property-info         v4.2.2  v4.2.2  Symfony Property Info Component
symfony/routing               v4.2.2  v4.2.2  Symfony Routing Component
symfony/security-acl          v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle       v4.2.2  v4.2.2  Symfony SecurityBundle
symfony/security-core         v4.2.2  v4.2.2  Symfony Security Component - Core Library
symfony/security-csrf         v4.2.2  v4.2.2  Symfony Security Component - CSRF Library
symfony/security-guard        v4.2.2  v4.2.2  Symfony Security Component - Guard
symfony/security-http         v4.2.2  v4.2.2  Symfony Security Component - HTTP Integration
symfony/serializer            v4.2.2  v4.2.2  Symfony Serializer Component
symfony/serializer-pack       v1.0.2  v1.0.2  A pack for the Symfony serializer
symfony/stopwatch             v4.2.2  v4.2.2  Symfony Stopwatch Component
symfony/swiftmailer-bundle    v3.2.5  v3.2.5  Symfony SwiftmailerBundle
symfony/templating            v4.2.2  v4.2.2  Symfony Templating Component
symfony/translation           v4.2.2  v4.2.2  Symfony Translation Component
symfony/twig-bridge           v4.2.2  v4.2.2  Symfony Twig Bridge
symfony/twig-bundle           v4.2.2  v4.2.2  Symfony TwigBundle
symfony/validator             v4.2.2  v4.2.2  Symfony Validator Component
symfony/var-dumper            v4.2.2  v4.2.2  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter          v4.2.2  v4.2.2  A blend of var_export() + serialize() to turn any serializable data s...
symfony/web-link              v4.2.2  v4.2.2  Symfony WebLink Component
symfony/web-profiler-bundle   v4.2.2  v4.2.2  Symfony WebProfilerBundle
symfony/web-server-bundle     v4.2.2  v4.2.2  Symfony WebServerBundle
symfony/webpack-encore-bundle v1.1.0  v1.1.0  Integration with your Symfony app & Webpack Encore!
symfony/workflow              v4.2.2  v4.2.2  Symfony Workflow Component
symfony/yaml                  v4.2.2  v4.2.2  Symfony Yaml Component

```

#### PHP version

```
$ php -v

PHP 7.1.25 (cli) (built: Dec  5 2018 06:50:31) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.25, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

Autowiring doesn't work: when you try to inject `MyAdmin` in another service, using the type hint. 

IMHO this can be easily fixed Use the original service id instead of the admin code in `AutoConfigureAdminClassesCompilerPass`. I'll make a PR.

## Steps to reproduce

- Create `MyAdmin` admin
- Create `MyListener`, and try to inject `MyAdmin` into the constructor

## Expected results

 `MyAdmin` admin is injected into `MyListener`.

## Actual results

> Cannot autowire service "App\EventListener\MyListener": argument "$myAdmin" of method "__construct()" references class "App\Admin\MyAdmin" but no such service exists. You should maybe alias this class to the existing "app.admin.my_admin" service.

### PR DESCRIPTION
**Pull request by gremo**
Closes #10

## Changelog

```markdown
### Changed
- use class name instead of admin code as service id
```

## Subject

Do **not use admin code as service id** and do **not compute admin code** if it's blank. This way Symfony 4 auto-wiring will work (injecting the admin in another service).

If admin code is provided, use it as **service id for the admin**. Creating an admin with an admin code that is different from service id is likely to create problems.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataAdminBundle/blob/ac77c9cd0ffec2e9bdffefeda7626c0c136f5545/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L67

Here you will see that sonata uses the same `$id` for service id and admin code, you will need to change this line too:

https://github.com/kunicmarko20/SonataAutoConfigureBundle/blob/80a0c00c51ffbe59a2eb9dd6b4688e910e8bdb7b/src/DependencyInjection/Compiler/AutoConfigureAdminClassesCompilerPass.php#L92

I am not sure if this will break something, hopefully, it won't but IIRC there was a reason I went with admin code instead of class as an id.

**Comment by gremo** [comment]
I think that we do need to change that line: if null, SonataAdminBundle will compute the admin code from service id. In my local fork of this bundle, it seems to work just fine.

**Comment by kunicmarko20** [comment]
> if null, SonataAdminBundle will compute the admin code from service id.

IIRC, CompilerPass in this bundle should run after the SonataAdminBundle passes, so SonataAdminBundle won't do that.

> In my local fork of this bundle, it seems to work just fine.

I need to add some integration tests, this is something that can break everything but without integration tests we have no idea.

**Comment by gremo** [comment]
> IIRC, CompilerPass in this bundle should run after the SonataAdminBundle passes, so SonataAdminBundle won't do that.

Nope, in `bundles.php` I have: `SonataAdminBundle`, `SonataAutoConfigureBundle` (in this order) and dumping the compiler passes gives me:

- "KunicMarko\SonataAutoConfigureBundle\DependencyInjection\Compiler\AutoConfigureAdminClassesCompilerPass::process" 
- "Sonata\AdminBundle\DependencyInjection\Compiler\AddDependencyCallsCompilerPass::process"

It does not depend on the bundles order (i switched them too). **I really don't know how order is computed**.

**Comment by kunicmarko20** [comment]
I think order doesn't matter in `bundles.php` because you set an explicit priority when adding compiler pass in the Bundle class

**Comment by kunicmarko20** [comment]
Ok then, I wrote this half a year ago, forgot something. then I guess we can leave it like this and let SonataAdmin replace the admin code, doesn't that mean that admin_code will always be replaced? and that there is no point in us actually setting it?

**Comment by gremo** [comment]
> Ok then, I wrote this half a year ago, forgot something. then I guess we can leave it like this and let SonataAdmin replace the admin code, doesn't that mean that admin_code will always be replaced? and that there is no point in us actually setting it?

It seems reasonable to me. I think that computing the admin code (when you don't set it using the annotation) is **out the scope of this bundle**, if and only if we are SURE of compiler pass priority system (that is run before SonataAdminBundle pass).

**Comment by kunicmarko20** [comment]
I will try to test this tonight or in the next few days, to confirm the priority and add some tests.

**Comment by kunicmarko20** [comment]
Just checked and you are right, auto configure compiler pass has higher priority which means it is run before sonata admin, that means admin code is useless here?

**Comment by gremo** [comment]
Well, not useless at all (you still get the ability to configure admin code) but... not something this bundle should care about. Bonus: can inject admin services using autowiring.

Merging is still up to you :) I really like this bundle and the way It helps reducing a lot of boilerplate code, and I mainly use Sonata Admin for my work. I can help maintaining your code.

**Comment by kunicmarko20** [comment]
> (you still get the ability to configure admin code)

This is not true since SonataAdmin Compiler pass overwrites it with service id, and since that is done after this bundle, it will always be overwritten:

https://github.com/sonata-project/SonataAdminBundle/blob/ac77c9cd0ffec2e9bdffefeda7626c0c136f5545/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L67

**Comment by gremo** [comment]
I'll check it again tomorrow but I'm pretty sure that with this PR, setting admin code will still work (and be honored).

**Comment by gremo** [comment]
> This is not true since SonataAdmin Compiler pass overwrites it with service id, and since that is done after this bundle, it will always be overwritten:

Yes, you are right, but look at this line:

https://github.com/kunicmarko20/SonataAutoConfigureBundle/blob/7da493319dcc57439065ac4ac9d1e170ba238775/src/DependencyInjection/Compiler/AutoConfigureAdminClassesCompilerPass.php#L88

I'm using the admin code as service id (**if admin code is provided**): then SonataAdmin compiler pass will use the service id as admin code, so in the end, admin code from annotation is honored.

**Comment by kunicmarko20** [comment]
Ah yes, ok. Then this is valid, could you just add a test where admin code is used as a service id?

**Comment by gremo** [comment]
It should be covered here by this test data:

https://github.com/kunicmarko20/SonataAutoConfigureBundle/blob/7da493319dcc57439065ac4ac9d1e170ba238775/tests/DependencyInjection/Compiler/AutoConfigureAdminClassesCompilerPassTest.php#L109

**Comment by kunicmarko20** [comment]
It isn't defined in that admin class, so it is still null and then replaced by the service id but that is normal behaviour? Can you just set some code in that admin class and just confirm it uses it and I will merge it

**Comment by gremo** [comment]
> It isn't defined in that admin class, so it is still null and then replaced by the service id but that is normal behaviour? Can you just set some code in that admin class and just confirm it uses it and I will merge it

- First data sample: `CategoryAdmin` has admin code ( `admin.category`): our compiler pass will set the service id to  `admin.category`, container has that service, SonataAdmin complier pass will use `admin.category` as admin code

- Second data sample: `AnnotationAdmin` doesn't have admin code: our compiler pass will set the service id the FQCN, container has that service, SonataAdmin complier pass will use FQCN as admin code

If you want more tests, let me know.

**Comment by kunicmarko20** [comment]
Ok,

https://github.com/kunicmarko20/SonataAutoConfigureBundle/blob/7da493319dcc57439065ac4ac9d1e170ba238775/tests/DependencyInjection/Compiler/AutoConfigureAdminClassesCompilerPassTest.php#L77

this parts covers it, right?

**Review by kunicmarko20 — APPROVED** [review]

**Comment by kunicmarko20** [comment]
This still is a bc break, what if we leave the admin code to define the id, but we add an alias to the class name, will that still allow autowiring?

**Comment by gremo** [comment]
> This still is a bc break, what if we leave the admin code to define the id, but we add an alias to the class name, will that still allow autowiring?

In this case, I don't know if the admin pool will recognize the service: tak a look here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/Pool.php#L273 will this work with an alias? I don't think so.

Also here, where the pool is populated with admin service ids: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L210

**Comment by kunicmarko20** [comment]
It should work, it just allows you to have 2 ids for 1 service.

**Comment by gremo** [comment]
> It should work, it just allows you to have 2 ids for 1 service.

But if you look and the compiler pass, only the service id is set in the pool:` $pool->addMethodCall('setAdminServiceIds', [$admins]);`, not the alias. It's just a plain array of service ids.

**Comment by kunicmarko20** [comment]
yes, so we leave `id` as admin code, but we add alias to the class, that means pool can fetch it and you can autowire it because of the alias

**Comment by kunicmarko20** [comment]
I will test it tonight but that should work

**Comment by gremo** [comment]
> yes, so we leave `id` as admin code, but we add alias to the class, that means pool can fetch it and you can autowire it because of the alias

Let me know! But I think this check will fail:

https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/Pool.php#L275

**Comment by kunicmarko20** [comment]
It shouldn't because the id will still be the admin code, and the pool will still have the admin codes, but if you typehint the class in the ctor, you will get it autowired. This is just blindly guessing, will have to confirm it to continue.

**Comment by gremo** [comment]
> It shouldn't because the id will still be the admin code, and the pool will still have the admin codes, but if you typehint the class in the ctor, you will get it autowired. This is just blindly guessing, will have to confirm it to continue.

Ok, let me know. I think that the downside of your idea is that you still need admin code (instead of the service FQCN) to enable extensions, i.e:

    extensions:
        App\Admin\Extension\MyExtension:
            admins:
                - app.admin.category

**Comment by kunicmarko20** [comment]
that is true :thinking:

**Comment by kunicmarko20** [comment]
I really want to avoid a BC break, not sure how many people are using this and if they will even notice :sweat_smile: but it is still in `0.*` phase so I guess this is acceptable

**Comment by OskarStark** [comment]
BC breaks are only dir Version 1.0 and upwards per Definition of semver ☝🏻
But yes you should have an eye on this

**Comment by kunicmarko20** [comment]
Thanks @gremo

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/SonataAutoConfigureBundle/releases/tag/0.4.0

**Pull request merged**
