### PR TITLE
Add showMosaicButton annotation option

### PR DESCRIPTION
**Pull request by gremo**
## Changelog

```markdown
### Added
- missing `showMosaicButton` option in the AdminOptions annotation
```

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by kunicmarko20 — COMMENTED** [review]
Can you check the tests, please?

**Comment by gremo** [comment]
Sorry, forgot tests, fixed thanks.Sorry, forgot tests, fixed thanks.

**Review by kunicmarko20 — APPROVED** [review]

**Comment by kunicmarko20** [comment]
Thank you @gremo

**Comment by gremo** [comment]
Thanks to you, maybe release 0.2.1? :)

**Comment by kunicmarko20** [comment]
I thought about doing that after you finish https://github.com/kunicmarko20/SonataAutoConfigureBundle/issues/7? if you are gonna do that

**Comment by kunicmarko20** [comment]
And it would probably be 0.3.0 :smile:

**Comment by gremo** [comment]
Well, I think there is nothing wrong pushing 0.2.1 for the new option, and then release 0.3.0... but it's up to you. By the way, my PR will not break BC, so it could be 0.2.2... do you agree?

**Comment by kunicmarko20** [comment]
there is no BC for `0.*`. But this is more of addition and your new PR also, so that would be `0.3` and then `0.4` release, that is why I wanted to put both into `0.3.0`.

**Pull request merged**
